[build]
  command = "cd client && bun install && bun run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.0.0"

# Кэширование статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование изображений
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование шрифтов
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование JS и CSS файлов
[[headers]]
  for = "*/index.*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*/index.*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Основной файл HTML - упрощенные настройки безопасности для отладки
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Перенаправления для robots.txt и sitemap.xml
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# Перенаправления для SPA (должно быть в конце)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Перенаправление для API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
